import { beforeAll,afterAll,describe,it,expect } from 'vitest'; import fs from 'node:fs'; import path from 'node:path';
let app:any,sqlite:any,cookie=''; const tmp=path.resolve('/tmp/leafmark-test.sqlite');
beforeAll(async()=>{for(const f of [tmp,tmp+'-wal',tmp+'-shm'])try{fs.unlinkSync(f)}catch{}process.env.NODE_ENV='test';process.env.DATABASE_PATH=tmp;process.env.CHILDREN='Gavin:1357';process.env.PARENT_PIN='2468';process.env.LOCAL_AI_BASE_URL='http://127.0.0.1:1/v1';process.env.AI_TIMEOUT_MS='30';const mod=await import('./index');app=mod.app;sqlite=mod.sqlite;await app.ready();const c=await app.inject({method:'GET',url:'/api/children'});const id=c.json().children[0].id;const login=await app.inject({method:'POST',url:'/api/auth/child',payload:{childId:id,pin:'1357'}});cookie=String(login.headers['set-cookie']).split(';')[0]});
afterAll(async()=>{await app?.close();sqlite?.close();for(const f of [tmp,tmp+'-wal',tmp+'-shm'])try{fs.unlinkSync(f)}catch{}});
function req(method:string,url:string,payload?:any){return app.inject({method,url,headers:{cookie},payload})}
describe('critical learning flow',()=>{
 it('requires child authorization',async()=>expect((await app.inject({method:'GET',url:'/api/dashboard'})).statusCode).toBe(401));
 it('preserves original writing and makes retries idempotent',async()=>{let r=await req('POST','/api/books',{isbn:'9780306406157',title:'Test Book',author:'A. Author',pageCount:200,source:'Manual'});expect(r.statusCode).toBe(200);const childBookId=r.json().childBookId;const clientId=crypto.randomUUID();r=await req('POST',`/api/books/${childBookId}/sessions`,{clientId,startPage:81});const sid=r.json().session.id;
   const premature=await req('POST',`/api/sessions/${sid}/comprehension`,{response:'Because he was worried.',mutationId:crypto.randomUUID()});expect(premature.statusCode).toBe(409);
   const finishId=crypto.randomUUID();r=await req('POST',`/api/sessions/${sid}/finish-reading`,{endPage:97,elapsedSeconds:901,mutationId:finishId});expect(r.statusCode).toBe(200);const duplicate=await req('POST',`/api/sessions/${sid}/finish-reading`,{endPage:97,elapsedSeconds:901,mutationId:finishId});expect(duplicate.json().duplicate).toBe(true);
   const recall='The main character hid the map because he thought someone was following him.';r=await req('POST',`/api/sessions/${sid}/recall`,{recall,mutationId:crypto.randomUUID()});expect(r.statusCode).toBe(200);expect(r.json().question.question).toBeTruthy();
   r=await req('POST',`/api/sessions/${sid}/comprehension`,{response:'I think he was scared because someone followed him.',mutationId:crypto.randomUUID()});expect(r.statusCode).toBe(200);expect(r.json().revisionPrompt).toBeTruthy();
   const revised=recall+' He kept looking behind him, which shows why he hid it.';r=await req('POST',`/api/sessions/${sid}/revision`,{revised,mutationId:crypto.randomUUID()});expect(r.statusCode).toBe(200);
   const j=sqlite.prepare('SELECT original_writing,revised_writing FROM journal_entries WHERE session_id=?').get(sid);expect(j.original_writing).toBe(recall);expect(j.revised_writing).toBe(revised);const b=sqlite.prepare('SELECT current_page FROM child_books WHERE id=?').get(childBookId);expect(b.current_page).toBe(98);
 });
 it('protects Parent Mode with a different credential',async()=>{expect((await app.inject({method:'GET',url:'/api/parent/evidence',headers:{cookie}})).statusCode).toBe(401);const p=await app.inject({method:'POST',url:'/api/auth/parent',payload:{pin:'2468'}});expect(p.statusCode).toBe(200);const pc=String(p.headers['set-cookie']).split(';')[0];expect((await app.inject({method:'GET',url:'/api/parent/evidence',headers:{cookie:pc}})).statusCode).toBe(200)});
});
