import { integer, sqliteTable, text, uniqueIndex, index } from 'drizzle-orm/sqlite-core';

export const children = sqliteTable('children',{id:integer('id').primaryKey({autoIncrement:true}),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>({name:uniqueIndex('children_name_uq').on(t.name)}));
export const books = sqliteTable('books',{id:integer('id').primaryKey({autoIncrement:true}),isbn:text('isbn').notNull(),title:text('title').notNull(),author:text('author').notNull().default('Unknown author'),edition:text('edition'),publisher:text('publisher'),publicationDate:text('publication_date'),pageCount:integer('page_count'),description:text('description'),coverUrl:text('cover_url'),source:text('source').notNull(),createdAt:text('created_at').notNull()},t=>({isbn:uniqueIndex('books_isbn_uq').on(t.isbn)}));
export const childBooks = sqliteTable('child_books',{id:integer('id').primaryKey({autoIncrement:true}),childId:integer('child_id').notNull().references(()=>children.id,{onDelete:'cascade'}),bookId:integer('book_id').notNull().references(()=>books.id,{onDelete:'restrict'}),status:text('status',{enum:['current','completed']}).notNull().default('current'),currentPage:integer('current_page'),currentChapter:text('current_chapter'),startedAt:text('started_at').notNull(),completedAt:text('completed_at')},t=>({childBook:uniqueIndex('child_books_child_book_uq').on(t.childId,t.bookId),byChild:index('child_books_child_idx').on(t.childId)}));
export const readingSessions = sqliteTable('reading_sessions',{id:integer('id').primaryKey({autoIncrement:true}),clientId:text('client_id').notNull(),childId:integer('child_id').notNull().references(()=>children.id,{onDelete:'cascade'}),childBookId:integer('child_book_id').notNull().references(()=>childBooks.id,{onDelete:'cascade'}),startedAt:text('started_at').notNull(),endedAt:text('ended_at'),elapsedSeconds:integer('elapsed_seconds').notNull().default(0),startPage:integer('start_page'),endPage:integer('end_page'),startChapter:text('start_chapter'),endChapter:text('end_chapter'),status:text('status',{enum:['reading','writing','complete']}).notNull().default('reading')},t=>({client:uniqueIndex('reading_sessions_client_uq').on(t.childId,t.clientId),childIdx:index('reading_sessions_child_idx').on(t.childId),bookIdx:index('reading_sessions_book_idx').on(t.childBookId)}));
export const journalEntries = sqliteTable('journal_entries',{id:integer('id').primaryKey({autoIncrement:true}),sessionId:integer('session_id').notNull().references(()=>readingSessions.id,{onDelete:'cascade'}),childId:integer('child_id').notNull().references(()=>children.id,{onDelete:'cascade'}),childBookId:integer('child_book_id').notNull().references(()=>childBooks.id,{onDelete:'cascade'}),initialRecall:text('initial_recall').notNull(),originalWriting:text('original_writing').notNull(),revisedWriting:text('revised_writing'),revisionPrompt:text('revision_prompt'),writingSkill:text('writing_skill'),supportLevel:text('support_level').notNull().default('independent_recall'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>({session:uniqueIndex('journal_entries_session_uq').on(t.sessionId),childIdx:index('journal_entries_child_idx').on(t.childId)}));
export const comprehensionAttempts = sqliteTable('comprehension_attempts',{id:integer('id').primaryKey({autoIncrement:true}),journalId:integer('journal_id').notNull().references(()=>journalEntries.id,{onDelete:'cascade'}),skill:text('skill').notNull(),difficulty:integer('difficulty').notNull(),question:text('question').notNull(),response:text('response'),requiresTextEvidence:integer('requires_text_evidence',{mode:'boolean'}).notNull().default(false),level:text('level'),evidencePresent:integer('evidence_present',{mode:'boolean'}),observationsJson:text('observations_json'),createdAt:text('created_at').notNull()},t=>({journal:uniqueIndex('comprehension_journal_uq').on(t.journalId)}));
export const journalRevisions = sqliteTable('journal_revisions',{id:integer('id').primaryKey({autoIncrement:true}),journalId:integer('journal_id').notNull().references(()=>journalEntries.id,{onDelete:'cascade'}),originalText:text('original_text').notNull(),revisedText:text('revised_text').notNull(),prompt:text('prompt').notNull(),skill:text('skill').notNull(),createdAt:text('created_at').notNull()},t=>({journal:index('revisions_journal_idx').on(t.journalId)}));
export const skillObservations = sqliteTable('skill_observations',{id:integer('id').primaryKey({autoIncrement:true}),childId:integer('child_id').notNull().references(()=>children.id,{onDelete:'cascade'}),domain:text('domain',{enum:['reading','writing']}).notNull(),skill:text('skill').notNull(),level:text('level',{enum:['developing','practicing','consistent','independent']}).notNull(),sourceId:integer('source_id').notNull(),observedAt:text('observed_at').notNull()},t=>({childSkill:index('skill_obs_child_skill_idx').on(t.childId,t.skill)}));
export const aiInteractions = sqliteTable('ai_interactions',{id:integer('id').primaryKey({autoIncrement:true}),childId:integer('child_id'),kind:text('kind').notNull(),model:text('model').notNull(),ok:integer('ok',{mode:'boolean'}).notNull(),latencyMs:integer('latency_ms'),errorCode:text('error_code'),createdAt:text('created_at').notNull()});
export const metadataCache = sqliteTable('metadata_cache',{isbn:text('isbn').primaryKey(),payloadJson:text('payload_json').notNull(),source:text('source').notNull(),cachedAt:text('cached_at').notNull()});
export const syncMutations = sqliteTable('sync_mutations',{id:integer('id').primaryKey({autoIncrement:true}),childId:integer('child_id').notNull(),mutationId:text('mutation_id').notNull(),kind:text('kind').notNull(),createdAt:text('created_at').notNull()},t=>({mutation:uniqueIndex('sync_mutation_uq').on(t.childId,t.mutationId)}));
