import { useEffect,useState } from 'react'; import { useNavigate } from 'react-router-dom'; import { Activity,ArrowLeft,BookOpenCheck,Brain,ExternalLink,FileText,LockKeyhole,ShieldCheck,Sparkles } from 'lucide-react'; import { api,json } from '../lib/api'; import { formatMinutes } from '@leafmark/shared'; import { Spinner } from '../components/Spinner';
type Tab='overview'|'development'|'evidence';
export function ParentMode(){const nav=useNavigate();const [authed,setAuthed]=useState(false),[pin,setPin]=useState(''),[error,setError]=useState(''),[children,setChildren]=useState<any[]>([]),[childId,setChildId]=useState<number|undefined>(),[data,setData]=useState<any>(null),[evidence,setEvidence]=useState<any[]>([]),[tab,setTab]=useState<Tab>('overview'),[loading,setLoading]=useState(true),[summary,setSummary]=useState<any>(null),[summaryBusy,setSummaryBusy]=useState(false);
 useEffect(()=>{Promise.all([api<any>('/api/auth/me').catch(()=>({session:null})),api<any>('/api/children')]).then(([me,c])=>{setChildren(c.children);setChildId(c.children[0]?.id);setAuthed(me.session?.role==='parent')}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(authed&&childId){setLoading(true);Promise.all([api<any>(`/api/parent/overview?childId=${childId}`),api<any>('/api/parent/evidence')]).then(([o,e])=>{setData(o);setEvidence(e.evidence)}).catch(()=>setAuthed(false)).finally(()=>setLoading(false))}},[authed,childId]);
 async function login(){setError('');try{await api('/api/auth/parent',json({pin}));setAuthed(true)}catch{setError('That Parent PIN didn’t match.')}}
 async function makeSummary(){if(!childId)return;setSummaryBusy(true);try{setSummary(await api(`/api/parent/summary?childId=${childId}`))}finally{setSummaryBusy(false)}}
 if(loading&&!authed)return <main className="parent-login"><Spinner/></main>;
 if(!authed)return <main className="parent-login"><button className="back-link" onClick={()=>nav('/')}><ArrowLeft/> Reader profiles</button><section><div className="parent-lock"><LockKeyhole/></div><p className="eyebrow">Protected area</p><h1>Parent Mode</h1><p>Reading development, writing development, evidence, and family settings live here.</p><label>Parent PIN<input className="pin-input" type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} onKeyDown={e=>e.key==='Enter'&&pin&&login()} autoFocus/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button full" disabled={!pin} onClick={login}>Open Parent Mode</button></section></main>;
 if(loading||!data)return <main className="parent-shell"><Spinner label="Reading the journal history"/></main>;
 const byDomain=(domain:string)=>Object.values(data.observations.filter((o:any)=>o.domain===domain).reduce((acc:any,o:any)=>{if(!acc[o.skill])acc[o.skill]=o;return acc},{})) as any[];
 return <main className="parent-shell"><header className="parent-top"><button className="back-link" onClick={async()=>{await api('/api/auth/logout',json({}));nav('/')}}><ArrowLeft/> Leave Parent Mode</button><div className="parent-brand"><ShieldCheck/><span>Leafmark</span><strong>Parent Mode</strong></div><label className="child-select">Viewing<select value={childId} onChange={e=>{setChildId(Number(e.target.value));setSummary(null)}}>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></header><nav className="parent-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><Activity/> Activity</button><button className={tab==='development'?'active':''} onClick={()=>setTab('development')}><Brain/> Development</button><button className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}><FileText/> Evidence Center</button></nav>
 {tab==='overview'&&<div className="parent-content"><header className="parent-heading"><p className="eyebrow">Reading activity</p><h1>{data.child.name}’s recent reading</h1><p>Patterns over time matter more than any single response.</p></header><section className="parent-stat-line"><div><span>Books finished</span><strong>{data.stats.booksFinished}</strong></div><div><span>Reading time</span><strong>{formatMinutes(data.stats.readingSeconds)}</strong></div><div><span>Journal entries</span><strong>{data.stats.journalEntries}</strong></div><div><span>Words written</span><strong>{Number(data.stats.wordsWritten).toLocaleString()}</strong></div></section><section className="activity-ledger"><header><h2>Recent sessions</h2></header>{data.recentSessions.length?data.recentSessions.map((s:any,i:number)=><div key={i}><time>{new Date(s.started_at).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</time><strong>{s.title}</strong><span>{s.start_page&&s.end_page?`pp. ${s.start_page}–${s.end_page}`:'Location recorded'}</span><span>{formatMinutes(s.elapsed_seconds)}</span></div>):<p>No completed sessions yet.</p>}</section><section className="parent-summary"><div><Sparkles/><div><h2>Structured parent summary</h2><p>Generated only from stored session and skill-observation data.</p></div></div>{summary?<div className="summary-paper"><p>{summary.summary}</p>{summary.strengths?.length>0&&<p><strong>Strengths:</strong> {summary.strengths.join(' ')}</p>}{summary.nextSteps?.length>0&&<p><strong>Next:</strong> {summary.nextSteps.join(' ')}</p>}</div>:<button className="secondary-button" disabled={summaryBusy} onClick={makeSummary}>{summaryBusy?'Summarizing…':'Create current summary'}</button>}</section></div>}
 {tab==='development'&&<div className="parent-content"><header className="parent-heading"><p className="eyebrow">Longitudinal observations</p><h1>Development, without fake precision.</h1><p>States reflect repeated observed work. They are instructional signals, not standardized scores.</p></header><DevelopmentSection title="Reading development" icon={<BookOpenCheck/>} items={byDomain('reading')}/><DevelopmentSection title="Writing development" icon={<FileText/>} items={byDomain('writing')}/></div>}
 {tab==='evidence'&&<div className="parent-content"><header className="parent-heading"><p className="eyebrow">Why are we practicing this?</p><h1>Evidence Center</h1><p>Every instructional strategy in Leafmark points back to an inspectable practice and source.</p></header><div className="evidence-list">{evidence.map(e=><article key={e.id}><div className="evidence-id">{e.id}</div><h2>{e.skill.replaceAll('_',' ')}</h2><p><strong>What it is:</strong> {e.skillDescription}</p><p><strong>Evidence-based practice:</strong> {e.instructionalMethod}</p><dl><div><dt>How Leafmark implements it</dt><dd>{e.appImplementation}</dd></div><div><dt>Grade applicability</dt><dd>{e.gradeRange}</dd></div><div><dt>How progress is observed</dt><dd>{e.measurementMethod}</dd></div><div><dt>Success looks like</dt><dd>{e.successCriteria}</dd></div></dl><a href={e.evidenceUrl} target="_blank" rel="noreferrer">{e.evidenceSource} <ExternalLink/></a></article>)}</div></div>}</main>}
function DevelopmentSection({title,icon,items}:{title:string;icon:any;items:any[]}){return <section className="development-section"><header>{icon}<h2>{title}</h2></header>{items.length?<div className="development-grid">{items.map((o:any)=><div key={o.skill}><span>{o.skill.replaceAll('_',' ')}</span><strong className={`level level--${o.level}`}>{o.level}</strong><small>Last observed {new Date(o.observed_at).toLocaleDateString()}</small></div>)}</div>:<p className="quiet-empty">Not enough observations yet. Leafmark waits for real work before making claims.</p>}</section>}
